### ISSUE TITLE
Can't not decode this file.

### ISSUE THREAD

**Issue by sealday** [devongovett/png.js#34]
![qq 20170601110555](https://cloud.githubusercontent.com/assets/4080924/26777611/78ba2a78-4a10-11e7-8354-3a9b21d8ed2a.png)
```javascript
Error: Invalid filter algorithm: 241
    at /path/to/my/project/png-node.js:242:21
    at Inflate.onEnd (zlib.js:227:5)
    at emitNone (events.js:72:20)
    at Inflate.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by sealday** [comment]
devongovett/png-stream can not decode this file too.
